export const AUTH_ROUTE = '/auth'
export const REGISTER_ROUTE = '/registration'
export const PASSWORD_RESET_ROUTE = '/password_reset'
export const PASSWORD_RESET_CHANGE_ROUTE = '/password_reset_change'
export const MANAGER_MAIN_ROUTE = '/manager_main'

export const MANAGER_MAIN_VEHICLES_ROUTE = '/manager_main_vehicles'
export const MANAGER_MAIN_FEEDBACK_ROUTE = '/manager_main_feedback'
export const MANAGER_MAIN_PROFILE_ROUTE = '/manager_main_profile'
export const MANAGER_MAIN_ROUTES_ROUTE = '/manager_main_routes'
export const MANAGER_MAIN_SUPPORT_ROUTE = '/manager_main_support'
export const MANAGER_MAIN_TC_ROUTE = '/manager_main_TC'
export const MANAGER_MAIN_VEHICLE_EDIT_ROUTE = '/manager_main_vehicle_edit'
export const MANAGER_MAIN_ROUTE_EDIT_ROUTE = '/manager_main_route_edit'

export const MODERATOR_MAIN_ROUTE = '/moderator_main'
export const MODERATOR_MAIN_TC_ROUTE = '/moderator_main_TC'
export const MODERATOR_MAIN_MANAGERS_ROUTE = '/moderator_main_managers'
export const MODERATOR_MAIN_USERS_ROUTE = '/moderator_main_users'
export const MODERATOR_MAIN_FEEDBACK_ROUTE = '/moderator_main_feedback'
export const MODERATOR_MAIN_PROFILE_ROUTE = '/moderator_main_profile'
export const MODERATOR_MAIN_SUPPORT_ROUTE = '/moderator_main_support'
