export const AUTH_ROUTE = '/auth'
export const REGISTER_ROUTE = '/registration'
export const PASSWORD_RESET_ROUTE = '/password_reset'
export const PASSWORD_RESET_CHANGE_ROUTE = '/password_reset_change'
export const MANAGER_MAIN_ROUTE = '/manager_main'